"""feat(scrape): add user_pages table for custom web scraping

Revision ID: 08f12848f0d1
Revises: f4c1e8b52a76
Create Date: 2026-09-08 13:31:20.758086

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '08f12848f0d1'
down_revision = 'f4c1e8b52a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_pages',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=True),
    sa.Column('selector', sa.String(length=256), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('etag', sa.String(length=256), nullable=True),
    sa.Column('last_modified', sa.String(length=256), nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'url', name='uq_user_page')
    )
    with op.batch_alter_table('user_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_pages_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_pages_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('user_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_pages_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_pages_deleted_at'))

    op.drop_table('user_pages')
    # ### end Alembic commands ###
