"""academic identifiers + multi-email

Revision ID: 1a11ff73541b
Revises: 4b3579876684
Create Date: 2026-05-18 22:26:51.014672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a11ff73541b'
down_revision = '4b3579876684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identifier_types',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('validation_regex', sa.String(length=255), nullable=True),
    sa.Column('is_unique_per_user', sa.Boolean(), nullable=False),
    sa.Column('verification_method', sa.String(length=32), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('identifier_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identifier_types_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_identifier_types_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('user_identifiers',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('identifier_type_id', sa.BigInteger(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['identifier_type_id'], ['identifier_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier_type_id', 'value', name='uq_id_type_value'),
    sa.UniqueConstraint('user_id', 'identifier_type_id', 'value', name='uq_user_id_type_value')
    )
    with op.batch_alter_table('user_identifiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_identifiers_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_identifiers_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###

    # --- Data migration ---
    # 1) Seed the canonical 'email' identifier type.
    conn = op.get_bind()
    conn.execute(sa.text("""
        INSERT INTO identifier_types
            (code, name, validation_regex, is_unique_per_user, verification_method,
             created_at, updated_at)
        VALUES
            ('email', 'Email', '^[^@]+@[^@]+\\.[^@]+$', false, 'email_link', now(), now())
    """))

    # 2) Copy every existing users.email into user_identifiers as the primary
    # verified row for that user. They're already operational users, asking
    # them to re-verify would be a UX regression.
    conn.execute(sa.text("""
        INSERT INTO user_identifiers
            (user_id, identifier_type_id, value, is_primary, is_verified, verified_at,
             created_at, updated_at)
        SELECT
            u.id,
            (SELECT id FROM identifier_types WHERE code = 'email'),
            u.email, true, true, now(),
            now(), now()
        FROM users u
        WHERE u.deleted_at IS NULL
    """))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_identifiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_identifiers_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_identifiers_deleted_at'))

    op.drop_table('user_identifiers')
    with op.batch_alter_table('identifier_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identifier_types_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_identifier_types_code'))

    op.drop_table('identifier_types')
    # ### end Alembic commands ###
