"""add doi to papers, etag/last_modified to user_feeds, share fields to collections

Revision ID: 26cccdefc6f7
Revises: c5e88a1f2d34
Create Date: 2026-07-29 16:35:05.225907

NOTE: this migration was originally autogenerated against a dev DB that was
missing every Faz-3 table (a mis-stamped local DB), so Alembic emitted
`create_table` for collections/scan_runs/user_digests/user_feeds/user_sources
— all of which its ancestors already create. Running the chain from a clean
DB therefore failed with "relation collections already exists". Rewritten to
add ONLY the genuinely new columns; the tables themselves come from the
earlier revisions in the chain.
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "26cccdefc6f7"
down_revision = "c5e88a1f2d34"
branch_labels = None
depends_on = None


def upgrade():
    # DOI — enables cross-source dedup (a paper on arXiv + PubMed shares a DOI).
    with op.batch_alter_table("papers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("doi", sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f("ix_papers_doi"), ["doi"], unique=False)

    # Conditional GET — store the validators so nightly fetches can send
    # If-None-Match / If-Modified-Since and skip unchanged feeds (304).
    with op.batch_alter_table("user_feeds", schema=None) as batch_op:
        batch_op.add_column(sa.Column("etag", sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column("last_modified", sa.String(length=256), nullable=True))

    # Public collection sharing. server_default so existing rows get is_public=false.
    with op.batch_alter_table("collections", schema=None) as batch_op:
        batch_op.add_column(sa.Column("share_token", sa.String(length=64), nullable=True))
        batch_op.add_column(
            sa.Column("is_public", sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.create_index(
            batch_op.f("ix_collections_share_token"), ["share_token"], unique=True
        )

    # Author following — the model shipped without a migration; this is the
    # only genuinely-new table (all the others already exist in the chain).
    op.create_table(
        "user_authors",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("author_name", sa.String(length=128), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "author_name", name="uq_user_author"),
    )
    with op.batch_alter_table("user_authors", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_authors_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_authors_user_id"), ["user_id"], unique=False)


def downgrade():
    op.drop_table("user_authors")

    with op.batch_alter_table("collections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_collections_share_token"))
        batch_op.drop_column("is_public")
        batch_op.drop_column("share_token")

    with op.batch_alter_table("user_feeds", schema=None) as batch_op:
        batch_op.drop_column("last_modified")
        batch_op.drop_column("etag")

    with op.batch_alter_table("papers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_papers_doi"))
        batch_op.drop_column("doi")
