"""add_doi_to_papers_and_etag_to_user_feeds

Revision ID: 26cccdefc6f7
Revises: c5e88a1f2d34
Create Date: 2026-07-29 16:35:05.225907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26cccdefc6f7'
down_revision = 'c5e88a1f2d34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_collection_user_name')
    )
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collections_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_collections_user_id'), ['user_id'], unique=False)

    op.create_table('scan_runs',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('new_items', sa.Integer(), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_runs_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_runs_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_scan_runs_user_started', ['user_id', 'started_at'], unique=False)

    op.create_table('user_digests',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('highlights', sa.JSON(), nullable=True),
    sa.Column('themes', sa.JSON(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'period', 'period_start', name='uq_user_digest_period')
    )
    with op.batch_alter_table('user_digests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_digests_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_digests_user_id'), ['user_id'], unique=False)

    op.create_table('user_feeds',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('etag', sa.String(length=256), nullable=True),
    sa.Column('last_modified', sa.String(length=256), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_feeds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_feeds_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_feeds_user_id'), ['user_id'], unique=False)

    op.create_table('user_sources',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source_name', name='uq_user_source')
    )
    with op.batch_alter_table('user_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sources_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sources_user_id'), ['user_id'], unique=False)

    op.create_table('collection_papers',
    sa.Column('collection_id', sa.BigInteger(), nullable=False),
    sa.Column('user_paper_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_paper_id'], ['user_papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'user_paper_id')
    )
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value_en', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('variants', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('translated_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doi', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('kind', sa.String(length=16), nullable=True))
        batch_op.alter_column('external_id',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_papers_doi'), ['doi'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_papers_doi'))
        batch_op.alter_column('external_id',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.drop_column('kind')
        batch_op.drop_column('doi')

    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.drop_column('translated_at')
        batch_op.drop_column('variants')
        batch_op.drop_column('value_en')

    op.drop_table('collection_papers')
    with op.batch_alter_table('user_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sources_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_sources_deleted_at'))

    op.drop_table('user_sources')
    with op.batch_alter_table('user_feeds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_feeds_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_feeds_deleted_at'))

    op.drop_table('user_feeds')
    with op.batch_alter_table('user_digests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_digests_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_digests_deleted_at'))

    op.drop_table('user_digests')
    with op.batch_alter_table('scan_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_scan_runs_user_started')
        batch_op.drop_index(batch_op.f('ix_scan_runs_user_id'))
        batch_op.drop_index(batch_op.f('ix_scan_runs_deleted_at'))

    op.drop_table('scan_runs')
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collections_user_id'))
        batch_op.drop_index(batch_op.f('ix_collections_deleted_at'))

    op.drop_table('collections')
    # ### end Alembic commands ###
