"""remove is_primary; add keywords; cleanup user.email duplicates

Revision ID: 66b5ff3b9659
Revises: 1a11ff73541b
Create Date: 2026-05-18 22:49:53.740186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66b5ff3b9659'
down_revision = '1a11ff73541b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keywords',
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_keywords_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_keywords_value'), ['value'], unique=True)

    op.create_table('user_keywords',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('keyword_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'keyword_id', name='uq_user_keyword')
    )
    with op.batch_alter_table('user_keywords', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_keywords_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_keywords_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('identifier_types', schema=None) as batch_op:
        batch_op.drop_column('is_unique_per_user')

    with op.batch_alter_table('user_identifiers', schema=None) as batch_op:
        batch_op.drop_column('is_primary')

    # ### end Alembic commands ###

    # --- Data correction ---
    # Previous migration (1a11ff73541b) copied users.email into user_identifiers
    # under the assumption that "primary" identifier would mirror auth email.
    # That conflated the two systems. user_identifiers is now strictly for
    # *historical / alternate* identities, never the login email — so drop
    # those duplicates here.
    conn = op.get_bind()
    conn.execute(sa.text("""
        DELETE FROM user_identifiers ui
        USING users u
        WHERE ui.user_id = u.id
          AND ui.value = u.email
          AND ui.identifier_type_id = (SELECT id FROM identifier_types WHERE code = 'email')
    """))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_identifiers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=False))

    with op.batch_alter_table('identifier_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_unique_per_user', sa.BOOLEAN(), autoincrement=False, nullable=False))

    with op.batch_alter_table('user_keywords', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_keywords_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_keywords_deleted_at'))

    op.drop_table('user_keywords')
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keywords_value'))
        batch_op.drop_index(batch_op.f('ix_keywords_deleted_at'))

    op.drop_table('keywords')
    # ### end Alembic commands ###
