"""papers + user_papers

Revision ID: a2d5a117ba89
Revises: 66b5ff3b9659
Create Date: 2026-05-19 17:57:23.787826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2d5a117ba89'
down_revision = '66b5ff3b9659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('authors', sa.JSON(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('pdf_url', sa.String(length=512), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_paper_source_external')
    )
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_papers_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_papers_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_papers_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_papers_source'), ['source'], unique=False)

    op.create_table('user_papers',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('paper_id', sa.BigInteger(), nullable=False),
    sa.Column('matched_keyword', sa.String(length=64), nullable=True),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'paper_id', name='uq_user_paper')
    )
    with op.batch_alter_table('user_papers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_papers_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_papers_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_papers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_papers_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_papers_deleted_at'))

    op.drop_table('user_papers')
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_papers_source'))
        batch_op.drop_index(batch_op.f('ix_papers_published_at'))
        batch_op.drop_index(batch_op.f('ix_papers_external_id'))
        batch_op.drop_index(batch_op.f('ix_papers_deleted_at'))

    op.drop_table('papers')
    # ### end Alembic commands ###
