"""Propagate the ScrapeMind mark from ``logo.svg`` to everywhere else.

The mark needs four shapes on disk and they must not drift apart, so exactly
one of them is written by hand -- ``app/core/static/img/logo.svg``, which
paints with ``currentColor`` -- and this script derives the rest:

* ``core/_logo.html``  -- inlined into the topbar. It has to be inline rather
  than an ``<img>``: an SVG loaded through ``<img>`` is its own document and
  cannot see the page's ``currentColor``, so the mark would render black.
* ``favicon.svg``      -- the same paths with the brand colour baked in, since
  a browser tab gives the mark no colour to inherit either.
* the two PNGs         -- Safari below 16.4 and the iOS home screen still want
  a bitmap. The beziers are flattened here rather than redrawn in Pillow, so
  the bitmap cannot disagree with the vector.

Run it after any change to the mark:

    venv/Scripts/python.exe scripts/render_favicon.py
"""

from __future__ import annotations

import re
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
IMG_DIR = ROOT / "app" / "core" / "static" / "img"
SOURCE = IMG_DIR / "logo.svg"
FAVICON = IMG_DIR / "favicon.svg"
PARTIAL = ROOT / "app" / "core" / "templates" / "core" / "_logo.html"

VIEWBOX = 64.0

# --brand-600 in theme.css. Bright enough to hold on both a light and a dark
# browser tab strip, which --brand-700 is not.
BRAND = "#A62F41"

# Rendered at this multiple and downsampled, which is what gives the curve its
# antialiased edge -- Pillow's polygon fill is hard-edged on its own.
SUPERSAMPLE = 8

SIZES = {
    "favicon-32.png": 32,
    "favicon-180.png": 180,
}

BANNER = "{# Generated by scripts/render_favicon.py from img/logo.svg - do not edit. #}"


def _cubic(p0, c0, c1, p1, steps=48):
    """Flatten one cubic bezier to a list of points, p0 excluded."""
    out = []
    for i in range(1, steps + 1):
        t = i / steps
        u = 1 - t
        x = u**3 * p0[0] + 3 * u**2 * t * c0[0] + 3 * u * t**2 * c1[0] + t**3 * p1[0]
        y = u**3 * p0[1] + 3 * u**2 * t * c0[1] + 3 * u * t**2 * c1[1] + t**3 * p1[1]
        out.append((x, y))
    return out


def _parse_path(d: str) -> list[tuple[float, float]]:
    """Flatten one SVG path into a polygon.

    Only the subset the mark actually uses is handled -- absolute M, C, L and
    Z. Anything else means the mark grew a command this script cannot see, so
    it raises rather than silently rendering a different shape than the vector.
    """
    tokens = re.findall(r"[MCLZmclz]|-?\d+(?:\.\d+)?", d)
    pts: list[tuple[float, float]] = []
    cur = (0.0, 0.0)
    i = 0
    while i < len(tokens):
        cmd = tokens[i]
        if cmd in "MmLl":
            cur = (float(tokens[i + 1]), float(tokens[i + 2]))
            pts.append(cur)
            i += 3
        elif cmd in "Cc":
            c0 = (float(tokens[i + 1]), float(tokens[i + 2]))
            c1 = (float(tokens[i + 3]), float(tokens[i + 4]))
            end = (float(tokens[i + 5]), float(tokens[i + 6]))
            pts.extend(_cubic(cur, c0, c1, end))
            cur = end
            i += 7
        elif cmd in "Zz":
            i += 1
        else:
            raise ValueError(f"unsupported path command {cmd!r} in {d!r}")
    return pts


def _read_paths() -> list[str]:
    paths = re.findall(r'<path d="([^"]+)"', SOURCE.read_text(encoding="utf-8"))
    if not paths:
        raise SystemExit(f"{SOURCE} does not look like the mark any more")
    return paths


def _shapes(paths: list[str]) -> str:
    return "\n".join(f'  <path d="{d}"/>' for d in paths)


def main() -> None:
    paths = _read_paths()
    body = _shapes(paths)

    # Size stays in CSS (.brand-mark) so one partial can serve every context.
    PARTIAL.write_text(
        f"{BANNER}\n"
        '<svg class="brand-mark" viewBox="0 0 64 64" fill="currentColor"'
        ' aria-hidden="true">\n'
        f"{body}\n"
        "</svg>\n",
        encoding="utf-8",
    )
    print(f"wrote {PARTIAL.relative_to(ROOT)}")

    FAVICON.write_text(
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" fill="{BRAND}">\n'
        f"{body}\n"
        "</svg>\n",
        encoding="utf-8",
    )
    print(f"wrote {FAVICON.relative_to(ROOT)}")

    polygons = [_parse_path(d) for d in paths]
    for name, size in SIZES.items():
        big = size * SUPERSAMPLE
        scale = big / VIEWBOX
        canvas = Image.new("RGBA", (big, big), (0, 0, 0, 0))
        draw = ImageDraw.Draw(canvas)
        for poly in polygons:
            draw.polygon([(x * scale, y * scale) for x, y in poly], fill=BRAND)
        canvas.resize((size, size), Image.LANCZOS).save(IMG_DIR / name)
        print(f"wrote img/{name} ({size}x{size})")


if __name__ == "__main__":
    main()
